## Questions to Answer
        
        ## 1.Which brewery produces the strongest beers by ABV%?
        ## 2.If you had to pick 3 beers to recommend using only this data, which would you pick?
        ## 3. Which of the factors (aroma, taste, appearance, palette) are most important in determining the overall quality of a beer?
## 4.Lastly, if I typically enjoy a beer due to its aroma and appearance, which beer style should I try?
        
        
### All of the Null Treatments and other subsettings have been copied from the EDA.ipynb jupyter notebook Please refer to that if you find any confusions

In [1]:
## Loading the important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import missingno as msno
import seaborn as sns
import sklearn
%matplotlib inline

In [9]:
df_raw = pd.read_csv('C:/Lean_Skill_InterviewTest/data/beer-review-data-set.csv')
df_raw["user_birthdayRaw"].fillna(0,inplace= True)
df_raw["review_text"].fillna(0,inplace= True)
df_raw["user_birthdayRaw"].fillna('unknwn',inplace= True)
df_raw["user_birthdayUnix"].fillna(0,inplace= True)
df_raw["user_gender"].fillna('unknwn',inplace= True)
df_raw["user_ageInSeconds"].fillna('0',inplace= True)
df_raw["user_profileName"].fillna('unknwn',inplace= True)
df_raw.isnull().sum()
df_raw.columns
### Reading the data and Treating all the null values in the data frame 
#df_raw.describe()

Index(['index', 'beer_ABV', 'beer_beerId', 'beer_brewerId', 'beer_name',
       'beer_style', 'review_appearance', 'review_aroma', 'review_overall',
       'review_palate', 'review_taste', 'review_text', 'review_timeStruct',
       'review_timeUnix', 'user_ageInSeconds', 'user_birthdayRaw',
       'user_birthdayUnix', 'user_gender', 'user_profileName'],
      dtype='object')

In [12]:
#### Lets group by all the beers based on these two factors 
cols = ['review_aroma', 'review_appearance', 'beer_style']
df_4 = df_raw[cols]
df_4.head()

   review_aroma  review_appearance               beer_style
0           4.0                4.0     Herbed / Spiced Beer
1           3.5                4.0      American Barleywine
2           4.0                3.5  American Pale Ale (APA)
3           3.0                3.0           Czech Pilsener
4           3.0                4.0         English Pale Ale

In [16]:
# Lets take the first ascending sorting by review aroma
df_4.groupby('beer_style')[['review_aroma', 'review_appearance']].mean().sort_values(by='review_aroma', ascending=False)[:10]

                                  review_aroma  review_appearance
beer_style
American Double / Imperial Stout      4.404672           4.317019
American Wild Ale                     4.266667           4.013333
English Barleywine                    4.233333           3.983333
Wheatwine                             4.218659           3.899417
Rauchbier                             4.201436           4.022914
Russian Imperial Stout                4.173474           4.215305
Rye Beer                              4.129889           4.154244
BiÃ¨re de Garde                       4.125000           3.750000
American Double / Imperial IPA        4.067026           3.989206
Baltic Porter                         4.053218           4.144802

In [17]:
# Lets take the first ascending sorting by review aroma
df_4.groupby('beer_style')[['review_aroma', 'review_appearance']].mean().sort_values(by='review_appearance', ascending=False)[:10]

                                  review_aroma  review_appearance
beer_style
American Double / Imperial Stout      4.404672           4.317019
Russian Imperial Stout                4.173474           4.215305
Oatmeal Stout                         3.812500           4.215278
Rye Beer                              4.129889           4.154244
Baltic Porter                         4.053218           4.144802
Belgian IPA                           4.015625           4.026042
Rauchbier                             4.201436           4.022914
Belgian Strong Pale Ale               4.032658           4.013514
American Wild Ale                     4.266667           4.013333
Black & Tan                           3.860825           4.010309

### ***Answer 4 : American Double / Imperial Stout High aroma and High appearence scores ***